import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  // 手动定义侧边栏结构
  tutorialSidebar: [
    {
          type: 'category',
          label: '代币化股票产品',
          items: [
            'products/aaplx',
        'products/abbvx',
        'products/abtx',
        'products/acnx',
        'products/ambrx',
        'products/amznx',
        'products/appx',
        'products/avgox',
        'products/aznx',
        'products/bacx',
        'products/brkbx',
        'products/cmcsax',
        'products/coinx',
        'products/crclx',
        'products/crmx',
        'products/crwdx',
        'products/cscox',
        'products/cvxx',
        'products/dfdvx',
        'products/dhrx',
        'products/gldx',
        'products/gmex',
        'products/googlx',
        'products/gsx',
        'products/hdx',
        'products/honx',
        'products/hoodx',
        'products/ibmx',
        'products/intcx',
        'products/jnjx',
        'products/jpmx',
        'products/kox',
        'products/linx',
        'products/llyx',
        'products/max',
        'products/mcdx',
        'products/mdtx',
        'products/metax',
        'products/mrkx',
        'products/mrvlx',
        'products/msftx',
        'products/mstrx',
        'products/nflxx',
        'products/nvdax',
        'products/nvox',
        'products/orclx',
        'products/pepx',
        'products/pfex',
        'products/pgx',
        'products/pltrx',
        'products/pmx',
        'products/qqqx',
        'products/spyx',
        'products/tmox',
        'products/tqqqx',
        'products/tslax',
        'products/unhx',
        'products/vx',
        'products/vtix',
        'products/wmtx',
        'products/xomx',
      ],
    },


    'faq',
    'compliance',
    {
      type: 'category',
      label: '法律文档',
      items: [
        'legal/privacy-policy',
        'legal/disclaimer',
        'legal/affiliate-disclosure',
      ],
    },
  ],
};

export default sidebars;
